#====================================================================
#loading packages and setting stan options
library(rstan)
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
#--------------------------------------------------------------------
#compiling the main Stan model
rt = stanc("model.stan", model_name = 'model')
sm = stan_model(stanc_ret = rt, verbose = TRUE)

#compiling the simpler Stan model (we use it in the mechanical advantage analysis)
rts = stanc("model.simple.stan", model_name = 'model')
sms = stan_model(stanc_ret = rts, verbose = TRUE)

#reading the data
dat = read.table("hfbs.dat.txt", header=TRUE, as.is=TRUE)

#--------------------------------------------------------------------
#function to generate the results table
axtract = function(x, parnames=NA, quantiles = c(c(0.025,0.5,0.975)))
{
  
  if(!is.na(parnames)[1])
    dat = data.frame(rstan::extract(x, pars = parnames))
  else
    dat = data.frame(rstan::extract(x))
  
  summ = t(apply(dat, 2, quantile, quantiles))
  
  res = list(summary = summ, MCMC = dat)
  
  class(res) = "axmcmc"
  return(res)
}
#====================================================================
#In the objects generated by the mcmc runs. The parameter names follow
#this code

#A - model intercepts
#B - model slopes
#SDA - sexual dimorphism in intercepts
#SDB - sexual dimorphism in slopes

#1.1 - A. abtao females
#1.2 - A. abtao males
#2.1 - A. longirostri females
#2.2 - A. longiristri males

#In the analysis of mechanical advantage, its only A. longirostri.
#So 1 and 2 are simply females and males.
#====================================================================
#################################
#Analysis of strength (apodeme)
#################################

#apodeme ~ claw centroid size (cs)

#putting all the data we need in a list
list.ap = list(N = nrow(dat),
               M = 2,
               y = dat$sqap,
               x = dat$center.csize,
               sp = dat$sp.number,
               sex = dat$sex.number)


#running the MCMC
initime = proc.time()
fit.ap = sampling(sm, data=list.ap, chains=3, iter = 20*1000)
runtime = proc.time()-initime

#extracting results
mcmc.ap = axtract(fit.ap)
mcmc.ap$summary


#apodeme ~ body size (cc)

list.apt = list(N = nrow(dat),
                M = 2,
                y = dat$sqap,
                x = dat$center.cc,
                sp = dat$sp.number,
                sex = dat$sex.number)

#running the MCMC
fit.apt = sampling(sm, data=list.apt, chains=3, iter = 20*1000)

mcmc.apt = axtract(fit.apt)
mcmc.apt$summary

#====================================================================

#####################################################
#MECHANICAL ADVANTAGE - ma ~ claw centroid size (cs)
#(only Aegla longirostri)
####################################################

list.maTL = list(N = sum(dat$species == "longirostri"),
                 M = 2,
                 y = dat$maT[dat$species == "longirostri"],
                 x = dat$center.csize[dat$species == "longirostri"],
                 cat = dat$sex.number[dat$species == "longirostri"])

fit.maTL = rstan::sampling(sms, data=list.maTL, chains=3, iter = 20*1000)

mcmc.maTL = axtract(fit.maTL)
mcmc.maTL$summary

#calculating sexual dimorphism
mc.maTL = as.data.frame(mcmc.maTL$MCMC)

mc.maTL$SDA = mc.maTL$A.2 - mc.maTL$A.1
mc.maTL$SDB = mc.maTL$B.2 - mc.maTL$B.1
head(mc.maTL)

#====================================================================

#################################################
#CLAW CENTROID SIZE - claw size ~ body sice (cc)
#################################################

list.cs = list(N = nrow(dat),
               M = 2,
               y = dat$csize,
               x = dat$center.cc,
               sp = dat$sp.number,
               sex = dat$sex.number)

fit.cs = rstan::sampling(sm, data=list.cs, chains=3, iter = 20*1000)

mcmc.cs = axtract(fit.cs)
mcmc.cs$summary

#====================================================================

##################################################
#CLAW SHAPE (PC1) - shape ~ claw centroid size
##################################################

list.pca = list(N = nrow(dat),
                M = 2,
                y = pca$pc.scores[,1]*-1,
                x = dat$center.csize,
                sp = dat$sp.number,
                sex = dat$sex.number)

#running the MCMC
initime = proc.time()
fit.pca = sampling(sm, data=list.pca, chains=3, iter = 20*1000)
runtime = proc.time()-initime

mcmc.pca = axtract(fit.pca)
mcmc.pca$summary

#====================================================================
#saving all fit data
#save(fit.ap, fit.apt, fit.maTL, fit.cs, fit.pca,
#     file = "hfbs.fits.RData")

#====================================================================